### ISSUE TITLE
Wrong SOVERSION

### ISSUE THREAD

**Issue by ErynGalen** [hyprwm/hyprutils#11]
https://github.com/hyprwm/hyprutils/blob/0252fd13e78e60fb0da512a212e56007515a49f7/CMakeLists.txt#L43
SOVERSION should be 0

EDIT: hyprcursor and xdg-desktop-portal-hyprland depend on libhyprutils.so.0 (on Archlinux at least), and a version of 0 matches the current major version of the package.

**Comment by vaxerski** [comment]
not understanding how soversions work doesn't mean they are wrong
