### ISSUE TITLE
CMake Error at build/cmake_install.cmake:57

### ISSUE THREAD

**Issue by raulhubgit** [hyprwm/hyprutils#15]
I have been trying to compile this for the past hour, yet it always returns this message no matter what i do, i already installed all dependencies
![Captura de tela de 2024-10-27 09-13-01](https://github.com/user-attachments/assets/906be204-4a8c-4f0d-b777-bd5e4b96a671)

**Comment by vaxerski** [comment]
you're trying to install without having built, most likely

**Comment by raulhubgit** [comment]
> you're trying to install without having built, most likely

Yeah, i finally figured out how to build this, thanks man

**Comment by AndreM222** [comment]
Um I run the command given at the readme file and I am getting this. what where you missing to build it?
