### ISSUE TITLE
Version 0.2.4 won't build in Windows because of fork() and use of signals

### ISSUE THREAD

**Issue by brechtsanders** [hyprwm/hyprutils#18]
When building version 0.2.4 for Windows with MinGW-w64 the build fails on `src/os/Process.cpp`.

The reasons are:
- missing `sys/wait.h`
- missing `fork()`
- use of signals

But I guess the whole way of spawning a process is different on Windows so this file probably needs a completely different approach on Windows.

See projects like https://github.com/DaanDeMeyer/reproc who already do this.

**Comment by vaxerski** [comment]
I don't care
