### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by bubba-champion** [hyprwm/hyprutils#20]
Hyprland starts with zombie processes, after which they remain until Hyprland is exited. After reverting https://github.com/hyprwm/hyprutils/commit/4c5f18d06b603b09c8ed9978e07bb768b042d7c9 and https://github.com/hyprwm/hyprutils/commit/8d21d1dfa91c9a2e7e65418c12eb3f913cc609b9, this issue is no longer reproducible. Screenshot of this issue: https://discord.com/channels/961691461554950145/961694014615208048/1305954135136272444

**Comment by vaxerski** [comment]
nice, me when the
