### ISSUE TITLE
Hyprland crashes with "stack smashing detected"

### ISSUE THREAD

**Issue by mexanoz** [hyprwm/hyprutils#23]
After c3331116ebd0b71df5ae8c6efe9a7f94148b03bf Hyprland is crashing on launch with the following in the stderr:
```
*** stack smashing detected ***: terminated
```
and a SIGABT.
Downgrading hyprutils to e6cf45cd1845368702e03b8912f4cc44ebba3322 helps.
Just in case: I compile all of the hypr ecosystem from AUR *-git packages using clang/lld/libstdc++ with LTO.

**Comment by vaxerski** [comment]
can't repro. Pretty sure you compiled something wrong.

**Comment by vaxerski** [comment]
yeah. the reason is miscompilation. Recompile the entire hypr* stack.
