### ISSUE TITLE
Missing libhyprutils.so.1

### ISSUE THREAD

**Issue by Da4ndo** [hyprwm/hyprutils#26]
The new version 0.3.0 no longer provides `libhyprutils.so.1`, which is required by Hyprland. I believe this is the reason why everyone, including myself, is now encountering the error: `Hyprland: error while loading shared libraries: libhyprutils.so.1: cannot open shared object file: No such file or directory.`

![image](https://github.com/user-attachments/assets/8c737cd8-91f8-4876-820a-4c681d0eae3d)

**Comment by vaxerski** [comment]
recompile hyprland then?

**Comment by Da4ndo** [comment]
Bro, I saw your previous comment on another forum. Recompiling Hyprland doesn't work. Also, from what I can see, the hyprutils package should provide the file, but it looks like that file is not included in the AUR.

**Comment by vaxerski** [comment]
Packaging is not something I am tasked with :)

I can assure you compilation does work unless you really have a broken system. Check out `hyprland-meta-git` in the aur
